# Generated by Django 5.1.9 on 2026-06-30 07:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="assets/")),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("product_image", "Product Image"),
                            ("design", "Design"),
                            ("thumbnail", "Thumbnail"),
                            ("render", "Render"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_size", models.IntegerField(default=0)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=50)),
                (
                    "checksum",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["asset_type"], name="products_as_asset_t_ed2ca3_idx"
                    ),
                    models.Index(
                        fields=["checksum"], name="products_as_checksu_2ce236_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                ("ordering", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["ordering", "name"],
            },
        ),
        migrations.CreateModel(
            name="CustomizationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "design_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Scale, rotation, position, alignment settings",
                    ),
                ),
                (
                    "output_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="generated_previews/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "share_token",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomizationVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField()),
                (
                    "design_settings",
                    models.JSONField(
                        default=dict,
                        help_text="Snapshot of design settings at this version",
                    ),
                ),
                (
                    "snapshot_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="version_snapshots/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="products.customizationjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="DesignUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="design_uploads/")),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("file_size", models.IntegerField(default=0)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=50)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="design_thumbnails/"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="customizationjob",
            name="design",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customizations",
                to="products.designupload",
            ),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("sku", models.CharField(blank=True, db_index=True, max_length=50)),
                (
                    "base_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_thumbnails/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sku", models.CharField(blank=True, db_index=True, max_length=50)),
                ("color", models.CharField(blank=True, max_length=50)),
                ("size", models.CharField(blank=True, max_length=20)),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_name", models.CharField(max_length=100)),
                (
                    "view_type",
                    models.CharField(
                        choices=[
                            ("front", "Front"),
                            ("back", "Back"),
                            ("left", "Left Side"),
                            ("right", "Right Side"),
                            ("custom", "Custom Angle"),
                        ],
                        default="front",
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="product_views/")),
                ("rotation_metadata", models.JSONField(blank=True, default=dict)),
                ("ordering", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering", "view_name"],
            },
        ),
        migrations.CreateModel(
            name="PrintArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, default="Main", max_length=100)),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("rotation", models.FloatField(default=0.0)),
                ("max_dpi", models.IntegerField(default=300)),
                ("is_default", models.BooleanField(default=True)),
                (
                    "product_view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_areas",
                        to="products.productview",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customizationjob",
            name="product_view",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customization_jobs",
                to="products.productview",
            ),
        ),
        migrations.CreateModel(
            name="RenderJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "render_type",
                    models.CharField(
                        choices=[
                            ("preview", "Preview"),
                            ("final", "Final Render"),
                            ("thumbnail", "Thumbnail"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quality", models.IntegerField(default=85)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                (
                    "output_image",
                    models.ImageField(blank=True, null=True, upload_to="renders/"),
                ),
                (
                    "render_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Timing, dimensions, pipeline details",
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="render_jobs",
                        to="products.customizationjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-queued_at"],
            },
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="products_ca_slug_da4386_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["parent", "ordering"], name="products_ca_parent__7b513d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customizationversion",
            unique_together={("job", "version_number")},
        ),
        migrations.AddIndex(
            model_name="designupload",
            index=models.Index(
                fields=["user", "-uploaded_at"], name="products_de_user_id_68c11d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="designupload",
            index=models.Index(fields=["status"], name="products_de_status_d22cdc_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="products_pr_slug_3edc0c_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="products_pr_categor_50f5f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created_at"], name="products_pr_created_bce1a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productview",
            index=models.Index(
                fields=["product", "view_type"], name="products_pr_product_4afcfb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="printarea",
            index=models.Index(
                fields=["product_view", "is_default"],
                name="products_pr_product_8fefe6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customizationjob",
            index=models.Index(
                fields=["user", "-created_at"], name="products_cu_user_id_d05f9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customizationjob",
            index=models.Index(fields=["status"], name="products_cu_status_4e13b9_idx"),
        ),
        migrations.AddIndex(
            model_name="customizationjob",
            index=models.Index(
                fields=["share_token"], name="products_cu_share_t_de32e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="renderjob",
            index=models.Index(
                fields=["customization", "render_type"],
                name="products_re_customi_ac9afb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="renderjob",
            index=models.Index(fields=["status"], name="products_re_status_6f51c6_idx"),
        ),
    ]
